services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: blogv2
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend




  minio:
    image: bitnami/minio:2022
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: supersecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - backend



  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - minio
    networks:
      - backend

volumes:
  db_data:
  minio_data:

networks:
  backend:
    driver: bridge
